stages:
  - ssh_gen
  - tf_plan
  - tf_apply
  - ans_config
  - tf_destroy

variables:
  TERRAFORM_VERSION:  1.8.2
  TF_ADDRESS: "https://gitlab.com/api/v4/projects/${PROJECT_ID}/terraform/state"

gen_ssh_keys:
  image: bash:latest
  stage: ssh_gen
  script:
    - apk update && apk add openssh-client
    - mkdir .keys && cd ./.keys
    - ssh-keygen -f vm_keys_${ENVIRONMENT} -q -t rsa -N "" && echo "Keys successfully generated"
  parallel:
    matrix: 
      - ENVIRONMENT: [dev, staging, prod]
  artifacts:
    name: ssh-keys
    expire_in: "1 day"
    paths: 
      - .keys

.provision:
  script:
    - apk update && apk upgrade
    - apk add unzip
    - wget -O terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_386.zip
    - unzip terraform.zip && mv ./terraform /bin
    - terraform -version
    - cd $ENVIRONMENT
    - sed -i 's#vm_keys.pub#vm_keys_'"${ENVIRONMENT}"'.pub#g' ../modules/debian_vm/variables.tf
    - sed -i 's#CREDENTIAL#'"${CREDENTIAL}"'#g' provider.tf
    - > 
        terraform init 
        -backend-config="address=${TF_ADDRESS}/${ENVIRONMENT}"
        -backend-config="lock_address=${TF_ADDRESS}/${ENVIRONMENT}/lock" 
        -backend-config="unlock_address=${TF_ADDRESS}/${ENVIRONMENT}/lock"
        -backend-config="username=root" 
        -backend-config="password=${GITLAB_ACCESS_TOKEN}" 
        -backend-config="lock_method=POST" 
        -backend-config="unlock_method=DELETE" 
        -backend-config="retry_wait_min=5"

dry_provision:
  image: alpine:3.18.2
  stage: tf_plan
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "gcp-terraform"
  script:
    - !reference [.provision, script]
    - terraform validate
    - terraform plan
  parallel:
    matrix: 
      - ENVIRONMENT: [dev, staging, prod]

actual_provision:
  image: alpine:3.18.2
  stage: tf_apply
  allow_failure: true
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "main"
  script:
    - !reference [.provision, script]
    - terraform apply -auto-approve
    - sleep 20
  parallel:
    matrix: 
      - ENVIRONMENT: [dev, staging, prod]
  artifacts:
    name: vm_ip
    expire_in: "1 day"
    paths:
      - '*_vm_ip.txt'

ansible_conf:
  image: python:3.9.17-slim-bullseye
  stage: ans_config
  allow_failure: true
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "main"
  script:
    - cat ${ENVIRONMENT}_vm_ip.txt >> vm_ip.txt
    - chmod 750 ansible_files
    - cd ansible_files
    - sed -i 's#vm_keys#vm_keys_'"${ENVIRONMENT}"'#g' ansible.cfg
    - apt-get update && apt-get install ansible -y
    - ansible --version
    - ansible-playbook ansible-playbook.yml
  parallel:
    matrix: 
      - ENVIRONMENT: [dev, staging, prod]

dry_destroy_tf:
  image: alpine:3.18.2
  stage: tf_destroy
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "main"
  script:
    - !reference [.provision, script]
    - terraform plan -destroy
  when: manual
  parallel:
    matrix: 
      - ENVIRONMENT: [dev, staging, prod]

actual_destroy_tf:
  image: alpine:3.18.2
  stage: tf_destroy
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "main"
  script:
    - !reference [.provision, script]
    - terraform destroy -auto-approve
  when: manual
  parallel:
    matrix: 
      - ENVIRONMENT: [dev, staging, prod]